import ast
import logging
import re

from multiqc.base_module import BaseMultiqcModule, ModuleNoSamplesFound
from multiqc.plots import bargraph

log = logging.getLogger(__name__)


class MultiqcModule(BaseMultiqcModule):
    """
    The module parses results generated by hicstuff pipeline command.
    hicstuff writes a summary stats dictionary to the log at the end of each run:

        ## hicstuff: v3.2.2 log file
        ## date: 2024-02-16 14:00:23
        ## enzyme: DpnII,HinfI
        ## input1: ../tinyMapper/tests/testHiC_R1.fq.gz
        ## input2: ../tinyMapper/tests/testHiC_R2.fq.gz
        ## ref: /home/rsg/genomes/S288c/S288c.fa
        ---
        ...
        2024-02-16,14:00:43 :: INFO :: 77% reads (single ends) mapped with Q >= 30 (154272/200000)
        2024-02-16,14:00:44 :: INFO :: 66943 pairs successfully mapped (66.94%)
        2024-02-16,14:00:46 :: INFO :: Fetching mapping and pairing stats
        2024-02-16,14:00:46 :: INFO :: {'Sample': 'testHiC^CGNT57', 'Total read pairs': 100000, 'Mapped reads': 154272, 'Unmapped reads': 45728, 'Recovered contacts': 66943, 'Final contacts': 66943, 'Removed contacts': 0, 'Filtered out': 0, 'Loops': 0, 'Uncuts': 0, 'Weirds': 0, 'PCR duplicates': 0}
        2024-02-16,14:00:46 :: INFO :: Contact map generated after 0h 0m 23s
    """

    def __init__(self):
        super().__init__(
            name="hicstuff",
            anchor="hicstuff",
            href="https://github.com/koszullab/hicstuff",
            info="Hi-C pipeline that generates contact maps from sequencing reads.",
            doi="10.5281/zenodo.4066363",
        )

        self.hicstuff_data = {}

        for f in self.find_log_files("hicstuff/pipeline_stats"):
            parsed = self.parse_hicstuff_log(f)
            if parsed is not None:
                s_name = self.clean_s_name(parsed["Sample"], f)
                self.hicstuff_data[s_name] = parsed
                self.add_data_source(f, s_name)
                if "version" in parsed:
                    self.add_software_version(str(parsed["version"]), sample=s_name)

        self.add_software_version(None)

        self.hicstuff_data = self.ignore_samples(self.hicstuff_data)

        if not self.hicstuff_data:
            raise ModuleNoSamplesFound

        log.info(f"Found {len(self.hicstuff_data)} reports")

        self.hicstuff_stats_table()
        self.hicstuff_read_fate_plot()
        self.write_data_file(self.hicstuff_data, "multiqc_hicstuff")

    def parse_hicstuff_log(self, f):
        """Parse a hicstuff log file and return the stats dict, or None if not found."""
        content = f["f"]
        version_match = re.search(r"^## hicstuff:\s+(v[\d.]+)", content, re.MULTILINE)
        stats_match = re.search(r"(\{'Sample':.*\})\s*$", content, re.MULTILINE)
        if stats_match is None:
            return None
        try:
            stats = ast.literal_eval(stats_match.group(1))
        except (ValueError, SyntaxError) as exc:
            log.error(f"Could not parse hicstuff stats dict: {exc}")
            return None
        if version_match:
            stats["version"] = version_match.group(1)
        return stats

    def hicstuff_stats_table(self):
        """Add hicstuff stats to the general stats table."""
        gstats = {}
        for s_name, data in self.hicstuff_data.items():
            n = data.get("Total read pairs", 0)
            if not n:
                continue
            recovered = data.get("Recovered contacts", 0)
            gstats[s_name] = {
                "total_read_pairs": n,
                "pct_mapped": data.get("Mapped reads", 0) / (2.0 * n) * 100.0,
                "pct_pcr_dups": (data.get("PCR duplicates", 0) / recovered * 100.0) if recovered else 0.0,
                "pct_final": data.get("Final contacts", 0) / n * 100.0,
            }

        headers = {
            "total_read_pairs": {
                "title": "Read pairs",
                "description": "Total number of read pairs sequenced",
                "scale": "Blues",
                "shared_key": "read_count",
                "hidden": True,
            },
            "pct_mapped": {
                "title": "% Mapped",
                "description": "Percentage of single-end reads mapped (Q ≥ 30)",
                "suffix": "%",
                "max": 100,
                "min": 0,
                "scale": "RdYlGn",
                "format": "{:,.1f}",
            },
            "pct_pcr_dups": {
                "title": "% PCR dups",
                "description": "Percentage of recovered contacts identified as PCR duplicates",
                "suffix": "%",
                "max": 100,
                "min": 0,
                "scale": "OrRd",
                "format": "{:,.1f}",
            },
            "pct_final": {
                "title": "% Final",
                "description": "Percentage of read pairs retained as final Hi-C contacts",
                "suffix": "%",
                "max": 100,
                "min": 0,
                "scale": "RdYlGn",
                "format": "{:,.1f}",
            },
        }

        self.general_stats_addcols(gstats, headers)

    def hicstuff_read_fate_plot(self):
        """Generate the read fate stacked bar chart."""
        keys = {
            "Final contacts": {"color": "#3a7d3d", "name": "Final contacts"},
            "Weirds": {"color": "#e8b372", "name": "Weirds"},
            "Uncuts": {"color": "#f58a50", "name": "Uncuts"},
            "Loops": {"color": "#f95422", "name": "Loops"},
            "PCR duplicates": {"color": "#8b3a39", "name": "PCR duplicates"},
            "Unpaired reads": {"color": "#545454", "name": "Unpaired reads"},
            "Unmapped reads": {"color": "#B0B0B0", "name": "Unmapped reads"},
        }

        plot_data = {}
        for s_name, data in self.hicstuff_data.items():
            if not data.get("Total read pairs"):
                continue
            mapped = data.get("Mapped reads", 0)
            recovered = data.get("Recovered contacts", 0)
            plot_data[s_name] = {
                "Final contacts": data.get("Final contacts", 0),
                "Weirds": data.get("Weirds", 0),
                "Uncuts": data.get("Uncuts", 0),
                "Loops": data.get("Loops", 0),
                "PCR duplicates": data.get("PCR duplicates", 0),
                "Unpaired reads": max(0.0, mapped / 2.0 - recovered),
                "Unmapped reads": data.get("Unmapped reads", 0) / 2.0,
            }

        self.add_section(
            name="Read fate",
            anchor="hicstuff-read-fate",
            description=(
                "Breakdown of read pairs by fate in the Hi-C pipeline. "
                "Values are expressed as read-pair equivalents and sum to the total read pairs."
            ),
            helptext="""
                **Unmapped reads** - single-end reads that failed to align to the reference genome
                (divided by 2 to give read-pair equivalents).

                **Unpaired reads** - mapped reads that could not be paired into a valid contact.

                **PCR duplicates** - contact pairs removed as PCR duplicates.

                **Loops** - pairs where both ends map to the same restriction fragment (self-ligation artefacts).

                **Uncuts** - pairs from adjacent fragments that were not digested (dangling ends).

                **Weirds** - pairs with an unexpected read orientation.

                **Final contacts** - pairs retained for the Hi-C contact map.
            """,
            plot=bargraph.plot(
                plot_data,
                keys,
                {
                    "id": "hicstuff_read_fate",
                    "title": "hicstuff: Read fate",
                    "ylab": "Read pairs",
                    "cpswitch": True,
                    "cpswitch_c_active": True,
                    "tt_decimals": 0,
                },
            ),
        )
